"""Where the ESMFold2 harnesses get their two shared inputs.

Seven oracles here compare against `esmfold2_reference.py`, and all seven used
to read two artifacts from a SCRATCHPAD path baked in as a string literal. That
made them unrunnable the moment the session that produced them ended -- which is
exactly the failure `dev/` being tracked is supposed to prevent: a harness in
the repository that cannot be re-run is a harness that cannot check a refactor.

So:

  * `state_dict(model)` builds the state dict from the CHECKPOINT, removing the
    `esmfold2_sd.npz` artifact entirely. `converters.esmfold2.load_esmfold2_checkpoint`
    already accepts a snapshot directory, and the base release lives only in the
    hub cache, so that is read off disk by glob (huggingface_hub is not in the
    GPU venv and must not be installed into it).
  * `native(model, target)` loads the native dump -- features, ESM-C hidden
    states, native coordinates and pLDDT -- from `dev/oracles/dumps/`, and if it
    is absent says exactly which command produces it instead of raising a
    FileNotFoundError on a path the reader has never heard of.

`dumps/` is gitignored (it holds .npz), which is correct: these are outputs of a
native run, regenerated by the producer, and they depend on a vendor venv.
"""
import glob
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
DUMPS = os.path.join(HERE, 'dumps')

_HUB = {
    'esmfold2': 'ESMFold2',
    'esmfold2_fast': 'ESMFold2-Fast',
    'esmfold2_exp': 'ESMFold2-Experimental',
    'esmfold2_exp_fast': 'ESMFold2-Experimental-Fast',
    'esmfold2_exp_cutoff2025': 'ESMFold2-Experimental-Cutoff2025',
    'esmfold2_exp_fast_cutoff2025': 'ESMFold2-Experimental-Fast-Cutoff2025',
    'esmfold2_lm600m': 'ESMFold2-Experimental-Fast-base600M-step1500k',
    'esmfold2_lm300m': 'ESMFold2-Experimental-Fast-base300M-step1500k',
}


def checkpoint_dir(model='esmfold2'):
  """-> a directory the converter can read, local snapshot or hub cache."""
  hub = _HUB[model]
  local = os.path.expanduser('~/esmfold2_variants/%s' % hub)
  if os.path.isdir(local):
    return local
  hits = sorted(glob.glob(os.path.expanduser(
      '~/.cache/huggingface/hub/models--biohub--%s/snapshots/*' % hub)))
  if not hits:
    raise SystemExit(
        'no weights for %s: neither ~/esmfold2_variants/%s nor a hub cache '
        'entry for biohub/%s. Fetch it from ~/venv_esm (which has '
        'huggingface_hub).' % (model, hub, hub))
  return hits[-1]


def state_dict(model='esmfold2'):
  """The variant's flat state dict, as the converters want it."""
  from converters import esmfold2 as CV
  return CV.load_esmfold2_checkpoint(checkpoint_dir(model))


def native(model='esmfold2', target='6mrr68'):
  """The native dump for (model, target), or the command that makes it."""
  path = os.path.join(DUMPS, 'esmfold2_%s_%s.npz' % (model, target))
  legacy = os.path.join(DUMPS, 'esmfold2_%s.npz' % target)   # the old filename
  for p in (path, legacy):
    if os.path.exists(p):
      return dict(np.load(p, allow_pickle=True))
  raise SystemExit(
      'no native dump at %s.\nProduce it with the vendor venv:\n'
      '    cd %s && ~/venv_esm/bin/python dev/oracles/esmfold2_oracle_6mrr.py'
      % (path, os.path.dirname(os.path.dirname(HERE))))


def atom_map(fb, f):
  """-> (ref_idx, our_flat): the same atoms, in each side's own flat indexing.

  MATCH BY NAME, NEVER BY POSITION. Our featuriser emits 574 atoms for 6MRR and
  ESMFold2's 573 -- ours carries the terminal OXT, whose PROTEIN_HEAVY_ATOMS
  table does not -- so aligning by position puts every atom after that one
  against its neighbour. `ref_idx` indexes the dump's flat (n_atoms,) layout and
  `our_flat` the ravelled dense (num_token, max_atoms) one.
  """
  import numpy as np

  def names(chars):
    ch = np.asarray(chars).astype(int)
    return ch.argmax(-1) if ch.ndim >= 3 and ch.shape[-1] > 8 else ch

  gn, rn = names(fb.ref_structure.atom_name_chars), names(f['ref_atom_name_chars'])
  gm = np.asarray(fb.ref_structure.mask).astype(bool)
  rm = np.asarray(f['atom_attention_mask']).astype(bool)
  r2t = np.asarray(f['atom_to_token']).astype(int)
  nm = lambda v: ''.join(chr(c + 32) for c in v).strip()

  by = {}
  for t in range(gn.shape[0]):
    for s in range(gn.shape[1]):
      if gm[t, s]:
        by.setdefault(t, {})[nm(gn[t, s])] = t * gn.shape[1] + s
  ref_idx, our_flat = [], []
  for i in np.flatnonzero(rm):
    slot = by.get(int(r2t[i]), {}).get(nm(rn[i]))
    if slot is not None:
      ref_idx.append(int(i)); our_flat.append(int(slot))
  return np.asarray(ref_idx), np.asarray(our_flat)
